### ISSUE TITLE
Wanted to compile & test locally but 2 years development had a toll on the code

### ISSUE THREAD

**Issue by large** [spydon/tumble_puzzle#1]
Is there an "easy" way to get this to run with todays standards. Or will old projects just be abandoned?

**Comment by spydon** [comment]
Have you tried to pin the dependencies in the pubspec file and run it with the specified Flutter version?

**Comment by spydon** [comment]
I have to go to bed now (Advent of Code problem releasing at 06:00 :sweat_smile:), but if you want to get this to run with the newest versions you can continue with my branch here, it at least starts but there is still some work to do:
https://github.com/spydon/tumble_puzzle/tree/bump-versions

**Comment by large** [comment]
That is just awesome @spydon 👍 

I tested the bump-version and I see it had to redo a-lot of code.
I have seen this in large amount of Flutter code these days, getting more mature I hope....
But it makes it really hard to actually "know" if the techniques used are modern enough to actually use.

Now I got a race-conditions because of a missing await; for instance 
https://github.com/spydon/tumble_puzzle/blob/522650db5a6232cd82bedb0f4a54d0222e1b550f/lib/game/tumble_puzzle_game.dart#L63 needs an await so the "body" exists.
+
https://github.com/spydon/tumble_puzzle/blob/522650db5a6232cd82bedb0f4a54d0222e1b550f/lib/game/tumble_puzzle_game.dart#L67
and
https://github.com/spydon/tumble_puzzle/blob/522650db5a6232cd82bedb0f4a54d0222e1b550f/lib/game/tumble_puzzle_game.dart#L70

Background, buttons etc works as expected, the alignment of the game did not.
Got stuck in the top left with a frame around it:
![image](https://github.com/user-attachments/assets/c473a2c5-0c65-4dd6-842f-5c8993c66bbc)

I am analysing the code to try to figure out why that happened.
No balls bounce around either ;)

Have not figured it out, but the bottom-right of bounderies is probably the one to blame:
https://github.com/spydon/tumble_puzzle/blob/522650db5a6232cd82bedb0f4a54d0222e1b550f/lib/game/boundaries.dart#L5

**Comment by spydon** [comment]
@large I fixed up the last things and pushed it to main. :)
The `DragArm` is still quite buggy though, but the game should be possible to play.

**Comment by large** [comment]
Awesome @spydon ! Thank you very much, what a service!
It shows the development in Flutter & Flame the past two years 👍
